version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.8
 build: 
  commands:
   - mkdir -p dependencies/python
   - pip install pyvips -t ./dependencies/python
   - cd ./dependencies && zip -r ../pyvips.zip .
   - cd ..
   - aws lambda publish-layer-version --layer-name test-pyvips --zip-file fileb://pyvips.zip --compatible-runtimes python3.8
   - cd stack
   - npm install aws-cdk
   - python -m pip install -r requirements.txt
   - npx cdk deploy -r "arn:aws:iam::977566059069:role/CloudformationPipelineRole" --require-approval never
