version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.8
 build: 
  commands:
   - cd stack
   - python -m venv .env
   - source .env/bin/activate
   - python -m pip install -r requirements.txt
   - cdk synth -o ../dist
artifacts:
 base-directory: dist
 files:
  - '**/*'
