version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.8
 build: 
  commands:
   - yum list installed
   - ls
   - cd stack
   - npm install aws-cdk
   - python -m pip install -r requirements.txt
   - npx cdk deploy -r "arn:aws:iam::977566059069:role/CloudformationPipelineRole" --require-approval never
