AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:

  contactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: contact.lambda_handler
      Runtime: python3.8
      FunctionName: contact
      CodeUri: ./src

  exchangeRatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getRates.lambda_handler
      Runtime: python3.8
      FunctionName: getRates
      CodeUri: ./src/ecommerce

  moreHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: moreHistory.lambda_handler
      Runtime: python3.8
      FunctionName: moreHistory
      CodeUri: ./src
