AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:

  SudoCoinsSurveyEndFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: survey_end.lambda_handler
      Runtime: python3.8
      FunctionName: SudoCoinsSurveyEnd
      CodeUri: ./src

  SudoCoinsTakeSurveyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: take_survey.lambda_handler
      Runtime: python3.8
      FunctionName: SudoCoinsTakeSurvey
      CodeUri: ./src

  SudoCoinsEndTransactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: end_transaction.lambda_handler
      Runtime: python3.8
      FunctionName: SudoCoinsEndTransaction
      CodeUri: ./src

  CashOutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cash_out.lambda_handler
      Runtime: python3.8
      FunctionName: SudoCoinsCashOut
      CodeUri: ./src

  UpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update_profile.lambda_handler
      Runtime: python3.8
      FunctionName: UpdateProfile
      CodeUri: ./src

  SetCurrencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: setCurrency.lambda_handler
      Runtime: python3.8
      FunctionName: setCurrency
      CodeUri: ./src

  contactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: contact.lambda_handler
      Runtime: python3.8
      FunctionName: contact
      CodeUri: ./src

  exchangeRatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getRates.lambda_handler
      Runtime: python3.8
      FunctionName: getRates
      CodeUri: ./src/ecommerce

  dynataRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dynataRedirect.lambda_handler
      Runtime: python3.8
      FunctionName: dynataRedirect
      CodeUri: ./src

  dynataCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dynataCallback.lambda_handler
      Runtime: python3.8
      FunctionName: dynataCallback
      CodeUri: ./src

  setConsentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: setConsent.lambda_handler
      Runtime: python3.8
      FunctionName: setConsent
      CodeUri: ./src

  getProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getProfile.lambda_handler
      Runtime: python3.8
      FunctionName: getProfile
      CodeUri: ./src

  moreHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: moreHistory.lambda_handler
      Runtime: python3.8
      FunctionName: moreHistory
      CodeUri: ./src

  checkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: checkout.lambda_handler
      Runtime: python3.8
      FunctionName: checkout
      CodeUri: ./src/ecommerce

  getGiftCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getGiftCard.lambda_handler
      Runtime: python3.8
      FunctionName: getGiftCard
      CodeUri: ./src/ecommerce

  setShippingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: setShipping.lambda_handler
      Runtime: python3.8
      FunctionName: setShipping
      CodeUri: ./src/ecommerce

  checkOrder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: checkOrder.lambda_handler
      Runtime: python3.8
      FunctionName: checkOrder
      CodeUri: ./src/ecommerce

  processOrder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: processOrder.lambda_handler
      Runtime: python3.8
      FunctionName: processOrder
      CodeUri: ./src/ecommerce

  addWallet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: addWallet.lambda_handler
      Runtime: python3.8
      FunctionName: addWallet
      CodeUri: ./src/ecommerce

  wyreCallback:
    Type: AWS::Serverless::Function
    Properties:
      Handler: wyreCallback.lambda_handler
      Runtime: python3.8
      FunctionName: wyreCallback
      CodeUri: ./src/ecommerce