AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:

  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Index.lambda_handler
      Runtime: python3.8
      FunctionName: SamplePython
      CodeUri: ./src

  SudoCoinsLoadProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: profile.lambda_handler
      Runtime: python3.8
      FunctionName: SudoCoinsLoadProfile
      CodeUri: ./src

  SudoCoinsSurveyEndFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: survey_end.lambda_handler
      Runtime: python3.8
      FunctionName: SudoCoinsSurveyEnd
      CodeUri: ./src

  SudoCoinsTakeSurveyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: take_survey.lambda_handler
      Runtime: python3.8
      FunctionName: SudoCoinsTakeSurvey
      CodeUri: ./src
