"""Code for supporting the lucid integration """


class Lucid:

    @staticmethod
    def region_code(region: str, language: str) -> int:
        return Lucid.locales.get(language + '-' + region)

    """Supported locales as provided by Lucid in clc.json"""
    locales = {
        'zh-CN': 1,
        'zh-Hans-CN': 1,
        'yue-CN': 161,
        'en-CN': 98,
        'zh-HK': 2,
        'zh-Hant-HK': 2,
        'en-HK': 73,
        'zh-TW': 3,
        'zh-Hant-TW': 3,
        'nl-NL': 4,
        'en-NL': 95,
        'en-AU': 5,
        'en-CA': 6,
        'fr-CA': 25,
        'zh-CA': 273,
        'zh-Hans-CA': 273,
        'en-IN': 7,
        'hi-IN': 76,
        'as-IN': 168,
        'bn-IN': 169,
        'doi-IN': 170,
        'gu-IN': 171,
        'kn-IN': 172,
        'ks-IN': 173,
        'kok-IN': 174,
        'mai-IN': 175,
        'mni-IN': 176,
        'mr-IN': 177,
        'ne-IN': 178,
        'or-IN': 179,
        'pa-IN': 180,
        'sa-IN': 181,
        'sat-IN': 182,
        'sd-IN': 183,
        'ta-IN': 184,
        'te-IN': 185,
        'ur-IN': 186,
        'en-GB': 8,
        'en-US': 9,
        'es-US': 27,
        'ko-US': 117,
        'vi-US': 118,
        'zh-Hans-US': 142,
        'ja-US': 143,
        'ar-US': 204,
        'fr-FR': 10,
        'en-FR': 99,
        'de-DE': 11,
        'en-DE': 74,
        'de-CH': 12,
        'fr-CH': 34,
        'it-CH': 35,
        'en-CH': 36,
        'it-IT': 13,
        'en-IT': 112,
        'ja-JP': 14,
        'en-JP': 113,
        'pl-PL': 15,
        'en-PL': 162,
        'pt-BR': 16,
        'en-BR': 108,
        'pt-PT': 17,
        'en-PT': 271,
        'ru-RU': 18,
        'en-RU': 100,
        'es-AR': 19,
        'en-AR': 107,
        'es-CO': 20,
        'en-CO': 109,
        'es-MX': 21,
        'en-MX': 115,
        'es-ES': 22,
        'en-ES': 119,
        'sv-SE': 23,
        'en-SE': 164,
        'ko-KR': 24
    }
